name: Metrics
on:
  schedule:
    - cron: "0 0 * * *" # Runs daily at midnight
  workflow_dispatch: # Allows you to run it manually

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: github-metrics-isocalendar.svg
          base: "" # Disables default stats to only show the calendar
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year # Displays a 12-month calendar
